describe('logs in, navigates to calendar, adds event', () => {
  it('logs in', () => {
    cy.visit('http://localhost:3000/#/')
    cy.get('#email')
      .type('q')
    cy.get('#password')
      .type('q')
    cy.get('button')
      .wait(1000)
      .click()
    cy.get('#calendar')
      .click()
    cy.get('.add-event-button')
      .click()
    cy.get('textarea')
      .type('This is my E2E test')
    cy.get('.create-event-button')
      .click()
    cy.get('.event-list-item')
      .first()
      .trigger('mouseover')
    cy.get('.fa-trash-alt')
      .first()
      .wait(2000)
      .click({ force: true})
    })
})
